version: 1

formatters:
  default:
    format: "[%(asctime)s][%(threadName)-8.8s][%(module)-8.8s][%(funcName)-12.12s][%(levelname)-4.4s] %(message)s"
  
    
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
    
  file:
    class: logging.handlers.RotatingFileHandler
    level: PROFILE
    formatter: default
    filename: /tmp/tycho
    encoding: utf8 
    maxBytes: 1048576 # 1Mb
    backupCount: 100
    
loggers:
  attribution:
    level: DEBUG
    handlers: [console, file]
    propagate: False
